import Link from "next/link";
import { ArrowLeft, Code2, Sparkles, UsersRound } from "lucide-react";
import { Logo } from "@/components/common/logo";

const creators = ["Tanisha Dey", "Aishgun Kaur", "Sudesna Mondal", "Abhinanda Bera", "Tanisha Chowdary", "Ruhaaba Warsi"];

export function CreatorsView() {
  return <main className="min-h-screen bg-[#090708] px-5 py-7 sm:px-8 lg:px-12"><div className="mx-auto max-w-[1320px]"><header className="flex items-center justify-between border-b border-white/[0.07] pb-5"><Logo /><Link href="/" className="focus-ring inline-flex min-h-10 items-center gap-2 text-xs text-[#807478] hover:text-white"><ArrowLeft className="size-4" />Back to EduFlow</Link></header><section className="grid gap-12 py-16 lg:grid-cols-[.85fr_1.15fr]"><div><p className="flex items-center gap-2 text-[10px] uppercase tracking-[.2em] text-[#A81736]"><Sparkles className="size-3.5" /> AI Enriched Project</p><h1 className="mt-5 font-[family-name:var(--font-display)] text-5xl font-semibold tracking-[-.055em] sm:text-7xl">Built by students, for students.</h1><p className="mt-6 max-w-xl text-base leading-7 text-[#9f9195]">EduFlow combines planning, practice, analytics, document understanding and an action-capable study copilot in one calm learning workspace.</p><div className="mt-9 border-l border-[#78152A] pl-5"><p className="text-xs uppercase tracking-[.16em] text-[#807478]">Project credit</p><p className="mt-2 text-sm leading-6 text-[#D8CDD0]">Made by Tanisha Dey, Aishgun Kaur, Sudesna Mondal, Abhinanda Bera, Tanisha Chowdary & Ruhaaba Warsi.</p></div></div><div className="grid gap-px border border-white/[0.08] bg-white/[0.08] sm:grid-cols-2"><div className="sm:col-span-2 bg-[#0d090a] p-6"><UsersRound className="size-5 text-[#A81736]" /><p className="mt-4 text-[10px] uppercase tracking-[.18em] text-[#807478]">Creator team</p></div>{creators.map((name, index) => <article key={name} className="bg-[#0b0809] p-6"><span className="text-[10px] text-[#62585b]">0{index + 1}</span><h2 className="mt-6 text-xl font-semibold tracking-[-.03em]">{name}</h2><p className="mt-2 flex items-center gap-2 text-xs text-[#807478]"><Code2 className="size-3.5" />EduFlow creator</p></article>)}</div></section></div></main>;
}
