"use client";
import { FormEvent, useEffect, useState } from "react";
import { ExternalLink, Search, Sparkles } from "lucide-react";
import { AppHeader } from "@/components/layout/app-header";
import { cloudFetch } from "@/lib/cloud/api-client";
import { useEduFlowStore } from "@/store/use-eduflow-store";
import type { ResearchResult } from "@/types/cloud";

export function ResearchView() {
 const profile=useEduFlowStore(s=>s.profile); const [query,setQuery]=useState(""); const [results,setResults]=useState<ResearchResult[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 useEffect(()=>{ const q=new URLSearchParams(window.location.search).get("q"); if(q) void search(undefined,q); },[]);
 const search=async(e?:FormEvent, directQuery?: string)=>{e?.preventDefault(); const term=(directQuery ?? query).trim(); if(term.length<2)return; if(directQuery) setQuery(term); setBusy(true);setError(""); try{const r=await cloudFetch(`/api/research/search?q=${encodeURIComponent(term)}`);const d=await r.json();if(!r.ok)throw new Error(d.error||"Search failed.");setResults(d.results||[])}catch(c){setError(c instanceof Error?c.message:"Search failed.")}finally{setBusy(false)}};
 return <main className="min-h-screen"><AppHeader name={profile?.name} context="Research"/><div className="mx-auto max-w-[1280px] px-4 py-8 sm:px-7 lg:px-10"><section className="border-b border-white/[0.08] pb-8"><p className="flex items-center gap-2 text-[10px] uppercase tracking-[.18em] text-[#807478]"><Sparkles className="size-3.5 text-[#A81736]"/>Real-world research</p><h1 className="mt-3 font-[family-name:var(--font-display)] text-4xl font-semibold tracking-[-.05em] sm:text-5xl">Search beyond the starter syllabus.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#9f9195]">EduFlow searches public knowledge and scholarly indexes from Wikipedia, OpenAlex and Crossref. Results remain source-linked so students can verify what they read.</p><form onSubmit={search} className="mt-7 flex max-w-3xl gap-2"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try: operating systems deadlock, photosynthesis, financial accounting…" className="focus-ring min-h-12 flex-1 border border-white/[0.1] bg-[#11090B] px-4 text-sm"/><button disabled={busy} className="focus-ring inline-flex min-h-12 items-center gap-2 bg-[#A81736] px-5 text-sm font-semibold text-white disabled:opacity-40"><Search className="size-4"/>{busy?"Searching…":"Search"}</button></form>{error?<p className="mt-3 text-xs text-[#e58b9c]">{error}</p>:null}</section><section className="py-7">{!results.length&&!busy?<div className="border-y border-white/[0.08] py-10 text-sm text-[#807478]">Search results will appear here with their original source links.</div>:<div className="divide-y divide-white/[0.07]">{results.map(item=><article key={item.id} className="grid gap-4 py-6 md:grid-cols-[120px_1fr_auto]"><div><span className="text-[9px] uppercase tracking-[.15em] text-[#A81736]">{item.source}</span>{item.year?<p className="mt-2 text-xs text-[#62585b]">{item.year}</p>:null}</div><div><h2 className="text-lg font-semibold">{item.title}</h2><p className="mt-2 text-sm leading-6 text-[#807478]">{item.snippet}</p>{item.authors?.length?<p className="mt-2 text-[10px] text-[#62585b]">{item.authors.join(" · ")}</p>:null}</div><a href={item.url} target="_blank" rel="noreferrer" className="focus-ring inline-flex min-h-10 items-center gap-2 text-xs text-[#B8AAAE] hover:text-white">Open source<ExternalLink className="size-3.5"/></a></article>)}</div>}</section></div></main>;
}
